---
yaml-files:
- '*.yaml'
- '*.yml'
- '.yamllint'
- '.markdown'

extends: default


rules:
  colons: disable
  document-end: disable
  line-length: disable
  new-line-at-end-of-file: disable
  trailing-spaces: disable
  
