name: Submeta sua sugestão
description: Submeta seus comentários para futuras edições do SREBrasilNoticias aqui
labels: [Sugestão de Artigos]
title: '[Preencha com sua sugestão de título]'
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por contribuir com a comunidade SREBrasil!
  - type: input
    id: contact
    attributes:
      label: Nome
      description: Qual seu nome? Queremos garantir que a comunidade reconheça sua contribuição!
      placeholder: ex. João da Silva
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. Isso será formatado automaticamente em código. Portanto, não há necessidade de barra inversa.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
