name: Submeta sua sugestão
description: Submeta seus comentários para futuras edições do SREBrasilNoticias aqui
labels: ["Sugestão de artigo"]
title: "[Sugestão de artigo]: Preencha com sua sugestão de título"
assignees: rcsousa
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por contribuir com a comunidade SREBrasil! 
        Preencha os campos abaixo para compartilhar seu ponto de vista com a comunidade.
  - type: input
    id: contact
    attributes:
      label: Nome
      description: Qual seu nome? Queremos garantir que a comunidade reconheça sua contribuição!
      placeholder: ex. João da Silva
    validations:
      required: false
  - type: input
    id: redesocial
    attributes:
      label: Qual seu perfil no LinkedIn ou Twitter?
      description: Ao compartilhar seu perfil social os membros da comunidade poderão se conectar com você e continuar a desenvolver o tema!
      placeholder: ex. http://linkedin.com/in/<seu perfil>
    validations:
      required: true
  - type: input
    id: titulooriginal
    attributes:
      label: Titulo original (em inglês ou portugês)
      description: Qual o título da puplicação original que você está comentando. Acreditamos que os creditos sempre devem ser atribuídos a quem de direito.
      placeholder: ex. The rise of a new standard to manage complex cloud systems - When innovation becomes mainstream
    validations:
      required: true
  - type: input
    id: autororiginal
    attributes:
      label: Autor(e)s
      description: Quem escreveu essa publicação. É importante atribuir os creditos aos criadores de conteúdo.
      placeholder: ex. Ricardo Coelho de Sousa
    validations:
      required: true
  - type: input
    id: urlroriginal
    attributes:
      label: URL da publicação original
      description: Qual o link (URL) da publicação original?
      placeholder: ex. https://www.detech.ai/blog/what-is-an-sre-product-managera
    validations:
      required: true
  - type: textarea
    id: comentarios
    attributes:
      label: Seus comentários
      description: O que você aprendeu, foi inspirador, e gostaria de compartilhar com a comunidade (em português)?
      placeholder: "Seja criativo. O que parece óbvio para você é muito valioso para outros"
      value: "Seja criativo. O que parece óbvio para você é muito valioso para outros"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Termo de conduta
      description: Ao submeter seus comentários você concorda eu inclui-los em uma versão futura do SREBrasilNoticias e assegura que seu texto não usa linguagem imprópria, violenta ou discriminatória com qualquer pessoa, independente de cor, raça, credo, gênero, ou orientação política.
      options:
        - label: Concordo com os termos de conduta
          required: true
