name: Atualiza README
on:
  workflow_dispatch:
  
  schedule:
    # Runs every day at 9AM UTC
    - cron: '0 4 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v1
        with:
          feed-url: https://destaque.srebrasil.com/feed.xml
          readme-section: feed
