name: Docker Image Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login no ghcr.io
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/rcsousa/srebrasilgithub:latest
    - name: Push image to repo
      run: docker push ghcr.io/rcsousa/srebrasilgithub:latest
