name: Nova Imagem Docker no Release

on:
  push:
    tags:
      - 'v[0-9]+[0-9]+.[0-9]+'
      
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login no ghcr.io
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/srebrasil/srebrasil.github.io:${GITHUB_REF#refs/*/}
    - name: Push image to repo
      run: docker push ghcr.io/srebrasil/srebrasil.github.io:${GITHUB_REF#refs/*/}
