name: Yaml Linter

on: push
  paths:
    - "**.markdown"
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, ubuntu-18.04]  # yamllint disable-line rule:line-length
    runs-on: ${{ matrix.os }}
    steps:
      - name: Installs the latest version of Yamllint
        run: pip install yamllint
      - name: Runs yamllint on all the yaml file of the repository
        run: yamllint --strict ./_posts/*.markdown
